#!/bin/sh
set -x

switch=br0

if [ -n "$1" ];then
        /usr/sbin/tunctl -t $1
        /sbin/ip link set $1 up
        sleep 1
        /sbin/brctl addif $switch $1
        exit 0
else
        echo "Error: no interface specified"
        exit 1
fi
