VAGRANTFILE_API_VERSION = "2"
#Vagrant.require_plugin "vagrant-libvirt"


Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

   config.ssh.username = "root"
   config.ssh.password = "vagrant"
    

   # -----------------------------------------------------#
   # 'controller' node
   # -----------------------------------------------------#
   config.vm.define "controller" do |controller|

          controller.vm.box = "deb-testing"
          controller.vm.hostname = "controller.demo"
          controller.vm.provider :libvirt do |domain|
            domain.memory = 2048
          end

          # network interfaces
           # management 
           controller.vm.network :private_network, ip: "10.0.0.11", :libvirt__network_name => 'management'

          # configuration
       
         # install puppet
          controller.vm.provision :shell , inline: "echo 'nameserver 192.168.4.1'> /etc/resolv.conf"
          controller.vm.provision "shell", inline: "hostname controller.demo && hostname > /etc/hostname"
          controller.vm.provision :shell , path: "provision/shell/enable-puppet.sh"
          controller.vm.provision :shell , path: "provision/shell/update-hosts"
          controller.vm.provision :shell , path: "provision/shell/install-puppet-openstack"
        
          controller.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hiera.yaml'
            file.destination = '/etc/puppet/hiera.yaml'
          end
          controller.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hieradb/common.yaml'
            file.destination = '/etc/puppet/hieradb/common.yaml'
          end
          controller.vm.provision 'puppet' do |puppet|
           puppet.manifests_path = 'provision/puppet/manifests'
           puppet.manifest_file = 'site.pp'
          end
          #controler.vm.provision "puppet"
   end

      

   # -----------------------------------------------------#
   # 'network' node
   # -----------------------------------------------------#

   config.vm.synced_folder ".", "/vagrant", disabled: true
 
   config.vm.define "network" do |network|

          network.vm.box = "deb-testing"
          network.vm.hostname = "network"
         
          network.vm.provider :libvirt do |domain|
            domain.memory = 512
          end
         
         # network interfaces
           # management
           network.vm.network :private_network, ip: "10.0.0.21", :libvirt__network_name => 'management'
           # instance tunnel
           network.vm.network :private_network, ip: "10.0.1.21", :libvirt__network_name => 'tunnels' 
           # external
           network.vm.network :public_network , :dev => 'eth1' 
         
         # configuration
          
         network.vm.provision :shell , inline: 'echo "nameserver 192.168.4.1"> /etc/resolv.conf'
         network.vm.provision "shell", inline: "hostname network.demo && hostname > /etc/hostname"
         # install puppet
         network.vm.provision :shell , path: "provision/shell/enable-puppet.sh"
         network.vm.provision :shell , path: "provision/shell/update-hosts"
         network.vm.provision :shell , path: "provision/shell/install-puppet-openstack"
         network.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hiera.yaml'
            file.destination = '/etc/puppet/hiera.yaml'
         end
         network.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hieradb/common.yaml'
            file.destination = '/etc/puppet/hieradb/common.yaml'
         end

         network.vm.provision 'puppet' do |puppet|
           puppet.manifests_path = 'provision/puppet/manifests'
           puppet.manifest_file = 'site.pp'
         end
         #network.vm.provision "puppet"

        
    end
   
   # -----------------------------------------------------#
   # 'compute1' node
   # -----------------------------------------------------#
   config.vm.define "compute1" do |compute1|

          compute1.vm.box = "deb-testing"
          compute1.vm.hostname = "compute1"
          compute1.vm.provider :libvirt do |domain|
            domain.memory = 2048
          end

          # network interfaces

           # management 
           compute1.vm.network :private_network, ip: "10.0.0.31", :libvirt__network_name => 'management'
           # instance tunnel
           compute1.vm.network :private_network, ip: "10.0.1.31", :libvirt__network_name => 'tunnels'

         # configuration
         # install puppet
          compute1.vm.provision :shell , inline: "echo 'nameserver 192.168.4.1'> /etc/resolv.conf"
          compute1.vm.provision "shell", inline: "hostname compute1.demo && hostname > /etc/hostname"
          compute1.vm.provision :shell , path: "provision/shell/enable-puppet.sh"
          compute1.vm.provision :shell , path: "provision/shell/update-hosts"
          compute1.vm.provision :shell , path: "provision/shell/install-puppet-openstack"
          compute1.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hiera.yaml'
            file.destination = '/etc/puppet/hiera.yaml'
          end
          compute1.vm.provision :file do |file|
            file.source      = 'provision/file/etc/puppet/hieradb/common.yaml'
            file.destination = '/etc/puppet/hieradb/common.yaml'
          end
          compute1.vm.provision 'puppet' do |puppet|
           puppet.manifests_path = 'provision/puppet/manifests'
           puppet.manifest_file = 'site.pp'
          end
          # compute1.vm.provision "puppet"
   end
   
end
